on: push

name: Check Package

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
        target:
          - x86_64-unknown-linux-gnu
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true

      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: check
          args: --target ${{ matrix.target }}